name: receipt_bot
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  google_generative_ai: ^0.4.7
  googleapis: ^13.0.0
  googleapis_auth: ^1.6.0
  http: ^1.2.0
  json_annotation: ^4.9.0
  pdf: ^3.10.0
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.4.8
  dart_frog_lint: ^0.1.0
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  test: ^1.25.5
